language: node_js
node_js:
  - lts/*
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  yarn: true
  directories:
    - node_module
    - ~/.npm
    - ~/.cache
install: yarn
script: yarn test:ci && yarn build
after_success:
  - yarn report-coverage
  - yarn semantic-release
