language: node_js
node_js:
  - lts/*
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
cache:
  directories:
    - node_module
    - ~/.cache
    - ~/.npm
script: npm run test:ci && npm run build
after_success:
  - npm run semantic-release
